### ISSUE TITLE
Folder Install gak ada

### ISSUE THREAD

**Issue by abmulyana** [garudacbt/cbt#2]
Bagaimana agar Garuda CBT bisa diinstall ?

**Comment by alittihad** [comment]
> Bagaimana agar Garuda CBT bisa diinstall ?
bisa diinstall menggunakan xampp, laragon atau linux server

**Comment by abmulyana** [comment]
Terima kasih untuk infonya. Saya sudah pake exam. Folder installnya apa
memang gak ada ya ?
Mohon infonya. Terima kasih.

**Comment by garudacbt** [comment]
aplikasi sudah diupdate, silakan download ulang atau bisa gabung di group telegram biar bisa saling sharing informasi
