### ISSUE TITLE
BUG Saat Installer

### ISSUE THREAD

**Issue by tahaluindo** [garudacbt/cbt#4]
Bang Bugnya Saat installer kok halaman setup.php tampilanya tidak responsive ya :)

**Comment by garudacbt** [comment]
coba diedit sendiri aja bugnya, mungkin perlu penyesuaian tampilan aja

**Comment by garudacbt** [comment]
aplikasi sudah diupdate, silakan download ulang atau bisa gabung di group telegram biar bisa saling sharing informasi
