### ISSUE TITLE
Tidak bisa membuat user siswa

### ISSUE THREAD

**Issue by MoMoSummer** [garudacbt/cbt#5]
Permisi, saat mau tambah user siswa, selalu muncul alert seperti ini, dan datanya tidak masuk ke database.
Lalu di user management, yang mengaktifkan user siswanya juga ndak bisa muncul user siswanya.
Mohon bantuannya, terima kasih.

![Untitled](https://user-images.githubusercontent.com/120610359/207743128-0a48f6ba-7aee-4b0b-80c4-0b836347b6ca.png)
![Untitled1](https://user-images.githubusercontent.com/120610359/207743432-2f13f065-fe6d-4645-a714-617d23a6cdff.png)

**Comment by garudacbt** [comment]
dicoba dulu import siswa pake file excel, atau bisa download ulang aplikasinya, aplikasi sudah diupdate pertanggal 17-01-2023

**Comment by MoMoSummer** [comment]
Terima kasih sudah menghubungi, baru saya download ulang, namun tetap tidak
bisa menginput dari web secara langsung. Berbeda kalau import lewat excel
bisa masuk, namun di user management tetap tidak muncul baik sebelum dan
sesudah diaktifkan. Terima kasih sudah meluangkan waktunya .

**Comment by garudacbt** [comment]
apa disimpan di hosting?
beberapa problem muncul karena pengaturan php dan mysql di hosting yg beda2.
di SS yg pertama itu ada data siswa yg nis/nisn ganda, solusinya bisa hapus paksa dari phpmyadmin.
di SS yg kedua ada pembatasan mysql perintah JOIN di hostingnya, bisa dicek pengaturan mysqlnya pada bagian MAX_JOIN_SIZE

silakan gabung di group telegram biar bisa saling sharing pengalaman

**Comment by betaalifuru83** [comment]
Saya juga mengalami hal yang sama seperti gambar 1 diatas, mohon solusinya minda.
