### ISSUE TITLE
PROBLEM

### ISSUE THREAD

**Issue by amarsenjaku** [garudacbt/cbt#7]
Assalamualikum Garudacbt,
Saya menemukan beberapa masalah kecil diantaranya:

1. Ketika Edit Rombel Kelas dihalaman admin lalu klik simpan maka akan generate rombel baru yang berisi jumlah siswa kosong dan nama kelas yang sama
2.  terkadang koreksi otomatis hasil ujian pada esay singkat belum akurat, dalam artian walaupun siswa sudah menjawab benar terkadang menjadi salah
3.  mungkin kedepannya agar waktu koreksi terdapat edit analisa juga

Terimakasih , Semoga menjadi platform yang membantu pendidikan dan semakin baik dan berkembang

**Comment by garudacbt** [comment]
mohon setakan screenshoot pak, supaya langsung bisa difahami bugsnya

**Comment by garudacbt** [comment]
silakan gabung di group telegram biar bisa saling sharing pengalaman

**Comment by ycusoy** [comment]
1. Mungkin bisa langsung delete yg tidk digunakan
2.  Essai? Susah diprediksi. Walaupun jawaban sama, kapital nya sama,. Maksudny? Atau katrol mungkin boleh
3.  ???

**Comment by garudacbt** [comment]
> Assalamualikum Garudacbt, Saya menemukan beberapa masalah kecil diantaranya:
> 
> 1. Ketika Edit Rombel Kelas dihalaman admin lalu klik simpan maka akan generate rombel baru yang berisi jumlah siswa kosong dan nama kelas yang sama
> 2. terkadang koreksi otomatis hasil ujian pada esay singkat belum akurat, dalam artian walaupun siswa sudah menjawab benar terkadang menjadi salah
> 3. mungkin kedepannya agar waktu koreksi terdapat edit analisa juga
> 
> Terimakasih , Semoga menjadi platform yang membantu pendidikan dan semakin baik dan berkembang

1. sudah fix
2. edit pontnya aja yg sesuai dgn jawaban
3. insyaAllah jika ada waktu
